<?xml version="1.0" encoding="utf-8"?><Database Name="Dados" Class="DadosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Dados.mdf;Integrated Security=True" SettingsObjectName="EmbalagemPremedidos.Properties.Settings" SettingsPropertyName="DadosConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Produto" Member="Produto">
    <Type Name="Produto">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodBarra" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PesoEmbalagem" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Descricao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>